export const HERO_QUERY = `*[_type == "hero"][0]{ text }`;
export const PROCESS_QUERY = `*[_type == "process"][0]{ main, subtext }`;
export const PROCESS_STEPS_QUERY = `*[_type == "process-steps"] | order(_createdAt asc){ _id, title, text }`;
export const CRITERIA_QUERY = `*[_type == "criteria"] | order(_createdAt asc){ _id, title, text }`;
export const LABEL_QUERY = `*[_type == "label"]{ _id, label, value }`;
export const FAQ_QUERY = `*[_type == "faq"]{ _id, question, answer }`;
export const ENDORSEMENT_QUERY = `*[_type == "endorsement"]{ _id, tier[0]->{ _id, label, value }, portrait, race, name, office, initials, pull, why, endorsed, positions[]->{ _id, yes, position } }`;
export const FOOTER_QUERY = `*[_type == "footer"][0]{ text }`;

export type Hero = { text: string };
export type Process = { main: string; subtext: string };
export type ProcessStep = { _id: string; title: string; text: string };
export type Criterion = { _id: string; title: string; text: string };
export type Label = { _id: string; label: string; value: string };
export type Faq = { _id: string; question: string; answer: string };
export type Position = { _id: string; yes: boolean; position: string };
export type Tier = { _id: string; label: string; value: string };
export type image = { _id: string; url: string };
export type Endorsement = {
  _id: string;
  tier: Tier;
  portrait: image;
  race: string;
  name: string;
  office: string;
  initials: string;
  pull: string;
  why: string;
  endorsed: boolean;
  positions: Position[];
};
export type Footer = { text: string };
